# Generated by Django 3.1.12 on 2026-01-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_calorie_goal',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
