# Generated by Django 3.1.12 on 2026-01-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260131_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('1.2', 'Sedentary (little or no exercise)'), ('1.375', 'Lightly active (light exercise 1-3 days/week)'), ('1.55', 'Moderately active (moderate exercise 3-5 days/week)'), ('1.725', 'Very active (hard exercise 6-7 days/week)'), ('1.9', 'Extra active (very hard exercise & physical job)')], default='1.2', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='calculated_bmr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='calculated_tdee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
