# Generated by Django 3.1.12 on 2026-01-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='meal',
            name='prep_time',
            field=models.IntegerField(default=15),
        ),
    ]
