# Generated by Django 3.1.12 on 2026-01-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20260131_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfoodlog',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Snack', max_length=20),
        ),
    ]
