# Generated by Django 3.1.12 on 2026-01-31 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_waterlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('Running', 'Running'), ('Cycling', 'Cycling'), ('Walking', 'Walking'), ('Swimming', 'Swimming'), ('Weight Training', 'Weight Training'), ('Yoga', 'Yoga'), ('HIIT', 'HIIT'), ('Dancing', 'Dancing'), ('Sports', 'Sports'), ('Other', 'Other')], max_length=50)),
                ('duration_minutes', models.IntegerField()),
                ('calories_burned', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
