# Generated by Django 3.1.12 on 2026-01-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_exerciselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfoodlog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='meal_photos/'),
        ),
    ]
